classificator: "sklearn.ensemble.RandomForestClassifier"
kwargs:
  n_estimators: 100
  max_depth: 10
  min_samples_split: 2
  min_samples_leaf: 1
  random_state: 42
  n_jobs: -1
  max_features: "sqrt"
  class_weight: "balanced"
